name: Web UI and API automation testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  APIwebUIAutoTest:
    runs-on: ubuntu-latest

    steps:
    #download repo
    - uses: actions/checkout@v4

    #setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    #setup gradle
    - name: Setup Gradle 8.5
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5
    - name: Build with Gradle 8.5
      run: gradle build

   #execute gradle command for running API test
    - name: Execute API test
      run: ./gradlew apiAutoTest
   #execute gradle command for running WEB UI test
    - name: Execute WEB UI test
      run: ./gradlew webUIAutoTest
      
   #archieve test result
    - name: Archive Test Result
      uses: actions/upload-pages-artifact@v3.0.1
      if: always()
      with: 
        name: API and WEB UI report
        path: reports

    #deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports
    
