name: Web UI and API automation testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  APIwebUIAutoTest:
    runs-on: ubuntu-latest

    steps:
    #download repo
    - uses: actions/checkout@v4

    #setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    #install browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    #setup gradlew
    - name: Setup gradlew
      run: chmod +x gradlew

   #execute gradle command fur running web UI and API test
    - name: Execute test
      run: ./gradlew APIwebUIAutoTest
      
 
